### PR TITLE
Replace ad-hoc std-based NAL with std-embedded-nal

### PR DESCRIPTION
**Pull request by chrysn**
Granted, std-embedded-nal is quite immature yet, but hey it works :-)

(If you like this but feel held back by the git= dependency, I'm happy to upload a 0.0.1, but didn't yet as it might get some vetting in the course of this PR.)

### CODE REVIEW

**Comment by ryan-summers** [comment]
I believe we're not able to publish to crates.io with any git= dependencies as is.

**Comment by chrysn** [comment]
If that's the only issue, that is about to be mitigated.

**Comment by chrysn** [comment]
There's a 0.0.1 on crates.io now; I've updated the PR accordingly, and tests here and in CI went through.

**Review by ryan-summers — APPROVED** [review]
:LGTM: Offloading the implementation of the stack here is definitely in our interest, as it helps to keep the focus on the test that is being performed.

Thanks for the change!

**Pull request merged**
